services:
  server:
    build: server
    image: shareitserver
    container_name: shareit-server
    ports:
      - "9090:9090"
    environment:
#      - TZ = Europe/Moscow
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=dan
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - db
    restart: on-failure

  gateway:
    build: gateway
    image: shareitgateway
    container_name: shareit-gateway
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
    depends_on:
      - server
    restart: on-failure
  db:
    image: postgres:16.1
    container_name: shareit-db
    ports:
      - "6541:5432"
    environment:
#      - TZ = Europe/Moscow
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dan
      - POSTGRES_DB=shareit
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
